using System;
using I2.Loc;
using Scythe.Multiplayer.Data;

namespace Scythe.Multiplayer
{
	// Token: 0x02000220 RID: 544
	public static class CreateRoomHelper
	{
		// Token: 0x0600101E RID: 4126 RVA: 0x0008F518 File Offset: 0x0008D718
		public static LobbyRoom CreateRoomWithPreferences(Preferences preferences)
		{
			return new LobbyRoom
			{
				AllRandom = true,
				ChoosingMats = false,
				InvadersFromAfar = preferences.IncludeDLC,
				IsAsynchronous = preferences.IsAsynchronous,
				IsPrivate = false,
				IsRanked = preferences.IsRanked,
				MaxELO = PlayerInfo.me.PlayerStats.ELO + 100,
				MaxPlayers = preferences.NumberOfPlayers,
				MinELO = PlayerInfo.me.PlayerStats.ELO - 100,
				Name = CreateRoomHelper.GetAutoGeneratedRoomName(),
				PlayerClockTime = PlayerTime.GetDefaultTimeInMinutes(preferences.IsAsynchronous),
				Players = 0,
				PromoCardsEnabled = true,
				RoomId = string.Empty
			};
		}

		// Token: 0x0600101F RID: 4127 RVA: 0x0008A8CC File Offset: 0x00088ACC
		private static string GetAutoGeneratedRoomName()
		{
			return string.Format("{0} {1} {2}", ScriptLocalization.Get("Common/Game"), PlayerInfo.me.PlayerStats.Name, DateTime.Now.ToShortDateString());
		}
	}
}
